config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations"}
  resources :users
  resources :products do
    resources :comments
  end
  
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'
  get 'simple_pages/contact'
  root 'simple_pages#landing_page'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  post 'payments/create'
  #get 'products/index'    
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommerceWebapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
      <a class="navbar-brand" href="https://bikesberlincom.herokuapp.com/"><%= image_tag "bikelogo.jpg", class: "img-fluid", width: "25px", height: "25px"%></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active"><%= link_to "Home", root_path %></li>
          <li class="nav-item"><%= link_to "About", simple_pages_about_path %></li>
          <li class="nav-item"><%= link_to "Contact", simple_pages_contact_path %></li>
          <li class="nav-item"><%= link_to "Products", products_path %></li>
          <li class="nav-item"><%= link_to "Orders", orders_path %></li>
          <li class="nav-item"><%= link_to "Users", users_path %></li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to('Login', new_user_session_path) %>
          </li>
          <% end %>
        </ul>
        
        <%# The search form %>
        <%= form_with(url: products_path, method: 'get', local: true) do |form| %>   
          <%= form.text_field :q, id: 'q', value: params[:q], class: 'search-field' %>
          <%= form.submit 'Search', class: 'btn btn-dark btn-sm' %>
        <% end %>
    </nav>

   
    <main class="container">
    <div id="alertmsg">
      <% if notice %>
        <p id="notice" class="alert alert-info" role="alert">
        <%= notice %>
        </p>
      <% end %>  
      <% if alert %>
          <p id="alert" class="alert alert-info" role="alert">
            <%= alert %>
          </p>
      <% end %>
    </div>
      
    <%# The yield tells the application where to render the view files inside the layout. %>
     <%= yield %>
    </main>
    
    <footer class="footer fixed-bottom">
      <div class="container">
        <span class="text-muted">&copy; 2018 Bike Berlin</span>
      </div>
    </footer>

  </body>
</html>